import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Header from '../../components/header/Header'
import Assignments from '../../components/assignments/Assignments'
import Assignments2 from '../../components/assignments/Assignments2'
import Assignments3 from '../../components/assignments/Assignments3'

const Dashboard : NextPage = () => {
    return (
        <div className={"w-screen h-screen bg-slate-100"}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="w-full h-full flex justify-start flex-col items-center flex-row">
                <Header />

                {/* Main Item Holder */}
                <div className="w-full flex flex-1 flex-row justify-start items-center">
                    <Assignments />
                    <Assignments2 />
                    <Assignments3 />
                </div>
                
            </main>
        </div>
    )
}

export default Dashboard
