import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import React, {
    FC, ReactNode, useContext, useEffect, useState
} from 'react';
import { AccountContext } from '../constants/cognito/Account';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

    return (
        <div>
            <Head>
                <title>Unidash</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className="relative w-screen h-screen flex flex-col justify-start items-center">
                {/* Wave */}
                <div className="z-0 absolute -top-14 left-0 right-0 h-full opacity-70 drop-shadow-xl">
                    <div className={`w-full ${styles.blurb} h-full`}></div>

                </div>

                {/* White Mini Wave */}
                <div className="absolute left-20 top-28 w-96 h-64">
                    <div className={`${styles.whiteWave} ml-20 scale-250 w-full h-full`}>

                    </div>
                </div>

                <MainHeader>
                    <DynamicButtons />
                </MainHeader>
                {/* First big block (2 parts) */}
                <div className="z-10 w-full h-full flex flex-row justify-start items-center">
                    {/* Tired of ____ */}
                    <div className="z-10 w-full xl:w-1/2 h-full flex flex-col justify-center items-center">
                        <div className="w-full flex flex-col justify-center items-start px-16">
                            <div className="flex flex-row justify-start items-center z-10">
                                <div className="text-sky-500">
                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-20 w-20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={4} d="M9 5l7 7-7 7" />
                                    </svg>
                                </div>
                                <div className="text-8xl font-bold text-slate-900">
                                    Tired of
                                </div>
                            </div>
                            {/* Iterating Text */}
                            <div className={`z-0 font-bold text-9xl relative`}>
                                <div className={`text-rose-500 absolute left-0 ${styles.tiredOfScroll1}`}>
                                    Blackboard<span className="text-rose-700">?</span>
                                </div>
                                
                                <div className={`text-purple-500 absolute left-0 ${styles.tiredOfScroll3}`}>
                                    Gradescope<span className="text-purple-700">?</span>
                                </div>
                                <div className={`text-amber-500 absolute left-0 ${styles.tiredOfScroll2}`}>
                                    Canvas<span className="text-amber-700">?</span>
                                </div>
                                <div className={`text-teal-500 absolute left-0 ${styles.tiredOfScroll4}`}>
                                    Turnitin<span className="text-teal-700">?</span>
                                </div>
                            </div>
                            {/* For Spacing bc of abolute positioning */}
                            <div className="text-9xl pointer-events-none opacity-0">
                                ㅤ
                            </div>
                            {/* <div className="flex flex-row justify-start items-center px-4 py-2 rounded-lg drop-shadow-lg bg-sky-500 ml-4 text-white font-medium text-4xl mt-20">
                                <div className="text-white">
                                    <svg xmlns="http://www.w3.org/2000/svg" className="h-9 w-9 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                                    </svg>
                                </div>
                                <div className="mr-2">
                                    We are, too.
                                </div>
                            </div> */}
                            <div className="flex flex-col justify-start items-center px-4 py-2 ml-4 text-slate-800 font-medium text-4xl mt-20 space-y-5">
                                <div className="flex flex-row justify-start items-start">
                                    {/* Icon */}
                                    <div className="mt-1 text-sky-500">
                                        <svg xmlns="http://www.w3.org/2000/svg" className="h-9 w-9 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                                        </svg>
                                    </div>

                                    {/* Text */}
                                    <div className="mr-2 flex flex-col justify-start items-start">
                                        We are, too. 
                                        <div>
                                            Enter{' '}<span className="font-bold text-sky-500">unidash.</span>
                                        </div>
                                    </div>
                                </div>
                                
                                {/* Signup button */}
                                <Link href="/signup">
                                    <div className={`${styles.cuteGradient} drop-shadow-md cursor-pointer w-full rounded-xl p-1 h-auto`}>
                                        <div className="w-full h-full bg-white rounded-lg">
                                            <div className={`bg-gradient-to-r from-sky-600 to-rose-600 bg-clip-text w-full h-full`}>
                                                <div className={`text-2xl text-center font-bold text-transparent px-2 py-1`}>
                                                    Start Now
                                                </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                    {/* <button className="transition duration-250 ease-in-out hover:drop-shadow-xl w-full rounded-lg drop-shadow-md border-2 border-sky-500 bg-white h-auto">
                                        <div className="text-2xl text-center font-medium text-sky-500 px-2 py-1">
                                            Start Now
                                        </div>
                                    </button> */}
                                </Link>
                            </div>
                        </div>
                        
                        
                    </div>

                    {/* Screenshot of Unidash UI */}
                    <div className="overflow-x-hidden scrollbar-hide w-1/2 h-full hidden xl:flex flex-col justify-center items-center">
                        
                        <div className={`${styles.previewImageParent} flex justify-center items-center w-full pr-32`}>
                            <div className={`overflow-x-clip  ${styles.previewImage} w-full aspect-video rounded-xl drop-shadow-lg flex justify-start flex-col items-center`}>
                                <div className="flex justify-center items-center relative h-full absolute scale-50" style={{
                                    width: '200%',
                                }}>
                                    <iframe
                                        className="w-full rounded-xl "
                                        src={'/demo'}
                                        style={{
                                            height: '200%'
                                        }}
                                    />
                                </div>
                                
                            </div>

                        </div>
                    </div>
                </div>
                
                {/* Seconds Big Block */}
                {/* <div className="w-full h-full flex flex-row justify-start items-center">
                
                </div> */}
            </div>
        </div>
    )
}

const DynamicButtons : FC = () => {

    const { getSession, logout } = useContext(AccountContext)

    const [isFetchingAuthState, setIsFetchingAuthState] = useState<boolean>(true);
    const [authed, setAuthed] = useState<boolean>(false);

    // Redirects us if we're already logged in
    useEffect(() => {

        setIsFetchingAuthState(true);

        (async () => {
            try {
                const session = await getSession();

                setAuthed(true)
            }
            catch (err) {

            }
            finally {
                setIsFetchingAuthState(false)
            }
        })();
    }, [])

    if (isFetchingAuthState) {
        return (
            <div>
                Loading...
            </div>
        )
    }
    else if (authed) {
        return (
            <>
                <div className="cursor-pointer h-auto w-auto px-2 py-1 border-2 border-sky-500 rounded-lg text-sky-500 flex justify-center items-center text-lg font-bold bg-white drop-shadow-md"
                onClick={() => {
                    logout();
                    setAuthed(false)
                }}
                >
                    Logout
                </div>
                <Link
                href="/dashboard"
                >
                    <div className="cursor-pointer h-auto w-auto px-2 py-1 border-2 border-sky-500 rounded-lg text-white flex justify-center items-center text-lg font-bold bg-sky-500 drop-shadow-md">
                        Dashboard
                    </div>
                </Link>
            </>
            
        )
    }
    else {
        return (
            <>
                <Link
                href="/signup"
                >
                    <div className="cursor-pointer h-auto w-auto px-2 py-1 border-2 border-sky-500 rounded-lg text-sky-500 flex justify-center items-center text-lg font-bold bg-white drop-shadow-md">
                        Sign up
                    </div>
                </Link>
                <Link
                href="/login"
                >
                    <div className="cursor-pointer h-auto w-auto px-2 py-1 border-2 border-sky-500 rounded-lg text-white flex justify-center items-center text-lg font-bold bg-sky-500 drop-shadow-md">
                        Login
                    </div>
                </Link>
            </>
        )
    }
}

interface MainHeaderProps {
    children?: ReactNode
}

export const MainHeader : FC<MainHeaderProps> = ({
    children
} : MainHeaderProps) => {
    return (
        <div className="z-10 w-full h-16 flex flex-row justify-between items-center px-10">
            {/* Logo + Name */}
            <div className="relative flex h-full flex-row justify-start items-center">
                <Link href={'/'}>
                    <div className="flex flex-row justify-start items-center space-x-1 cursor-pointer">
                        <div className="z-10 text-slate-800 mt-1">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                            </svg>
                        </div>
                        <div className="text-slate-800 text-3xl font-medium drop-shadow-md">
                            <span className="font-bold text-sky-500">uni</span>dash.
                        </div>
                    </div>
                </Link>
                
            </div>
            {/* Login/Signup/Dashboard */}
            <div className="flex flex-row justify-start items-center space-x-4">
                {
                    children ? children :
                    <>
                        <Link
                        href="/signup"
                        >
                            <div className="cursor-pointer h-auto w-auto px-2 py-1 border-2 border-sky-500 rounded-lg text-sky-500 flex justify-center items-center text-lg font-bold bg-white drop-shadow-md">
                                Sign up
                            </div>
                        </Link>
                        <Link
                        href="/login"
                        >
                            <div className="cursor-pointer h-auto w-auto px-2 py-1 border-2 border-sky-500 rounded-lg text-white flex justify-center items-center text-lg font-bold bg-sky-500 drop-shadow-md">
                                Login
                            </div>
                        </Link>
                    </>
                }
                
            </div>
        </div>
    )
}

export default Home
