import type { NextPage } from 'next'
import Head from 'next/head'
import React, {
    FC
} from 'react';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Unidash</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className="w-screen h-screen flex flex-col justify-start items-center">
                <Header />
                {/* First big block (2 parts) */}
                <div className="w-full h-full flex flex-row justify-start items-center">
                    {/* Tired of ____ */}
                    <div className="w-1/2 h-full flex flex-col justify-center items-center">
                        <div className="w-full flex flex-col justify-center items-start px-16">
                            <div className="z-10 text-8xl font-bold text-slate-900">
                                Tired of
                            </div>
                            {/* Iterating Text */}
                            <div className={`z-0 font-bold text-9xl relative`}>
                                <div className={`text-rose-500 absolute left-0 ${styles.tiredOfScroll1}`}>
                                    Blackboard<span className="text-slate-700">?</span>
                                </div>
                                
                                <div className={`text-purple-500 absolute left-0 ${styles.tiredOfScroll3}`}>
                                    Gradescope<span className="text-slate-700">?</span>
                                </div>
                                <div className={`text-amber-500 absolute left-0 ${styles.tiredOfScroll2}`}>
                                    Canvas<span className="text-slate-700">?</span>
                                </div>
                                <div className={`text-teal-500 absolute left-0 ${styles.tiredOfScroll4}`}>
                                    Turnitin<span className="text-slate-700">?</span>
                                </div>
                            </div>
                            {/* For Spacing bc of abolute positioning */}
                            <div className="text-9xl pointer-events-none opacity-0">
                                ㅤ
                            </div>
                            <div className="text-slate-900 font-medium text-4xl mt-20">
                                We are, too.
                            </div>
                        </div>
                        
                        
                    </div>

                    {/* Screenshot of Unidash UI */}
                    <div className="w-1/2 h-full flex flex-col justify-center items-center">
                        <div className="w-full px-16">
                            <div className="aspect-video bg-sky-300 rounded-xl drop-shadow-lg">

                            </div>

                        </div>
                    </div>
                </div>
                

            </div>
        </div>
    )
}

const Header : FC = () => {
    return (
        <div className="w-full h-16 flex flex-row justify-between items-center px-10">
            <div className="h-auto w-auto px-2 py-1 border-2 border-sky-500 rounded-lg text-white flex justify-center items-center text-lg font-bold bg-sky-500 drop-shadow-md">
                Login
            </div>
        </div>
    )
}

export default Home
